


steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']





- name: 'node'
  entrypoint: 'ls'

- name: 'node'
  entrypoint: 'pwd'

- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']

- name: 'node'
  entrypoint: 'ls'


- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', '-r', 'build/*', 'gs://samyfadel/']