


steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']


- name: 'node'
  entrypoint: 'ls'


- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', 'build/', 'gs://samyfadel']